package com.doctorpal.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Document(collection = "ipd_charges")
@Data @Builder @NoArgsConstructor @AllArgsConstructor
public class IpdCharge {
    @Id
    private String id;
    private String admissionId;
    private String doctorId;
    private ChargeType chargeType;
    private String description;
    private Double amount;
    private Integer quantity;
    private LocalDate chargeDate;
    private boolean isAutoGenerated;
    @CreatedDate
    private LocalDateTime createdAt;

    public enum ChargeType {
        BED, MEDICINE, DOCTOR_VISIT, INVESTIGATION, PROCEDURE, OTHER
    }
}