spring.application.name=doctorpal

# MongoDB
#spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/doctorpal}
spring.data.mongodb.uri=mongodb+srv://doctorpal_dev:Originals777@transport-cluster.aqzl8dv.mongodb.net/doctorpal?appName=transport-cluster
spring.data.mongodb.database=${MONGO_DB:doctorpal}

# JWT
app.jwt.secret=${JWT_SECRET:DoctorPalSuperSecretKeyForJWTTokenGeneration2024!}
app.jwt.expiration=${JWT_EXPIRATION:86400000}

# Server
server.port=${PORT:8080}

# Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# CORS
app.cors.allowed-origins=${CORS_ORIGINS:http://localhost:5173,http://localhost:3000}

# Logging
logging.level.com.doctorpal=DEBUG
logging.level.org.springframework.security=INFO
